"""Generate the zsh completion file from the parser itself.

Hand-maintaining `completions/_superday` alongside `build_parser()` is a
losing game: the rule "every subcommand needs a completion entry" has already
been broken and caught late more than once, because nothing enforces it. The
parser is the only thing that actually knows what the commands are, so the
completion is derived from it and the checked-in file is verified against the
generated one by `selftest`. Drift is now a failing test, not a discovery.

Regenerate with:  superday completions --write
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "completions" / "_superday"

HEADER = """#compdef superday sd ./superday
#
# Generated by `superday completions --write` from ib/cli.py's parser.
# Do not hand-edit: `superday selftest` fails when this file and the parser
# disagree, and a hand-edit is exactly how they come to disagree.

_superday() {
  local -a subcmds
  subcmds=(
"""

FOOTER = """  esac
}

_superday "$@"
"""

# Values worth offering by name rather than leaving the user to type.
DYNAMIC = {
    "path": "_files",
    "out": "_files",
}


def _zq(text) -> str:
    """Quote a string for inclusion inside single quotes in zsh.

    A metavar is a tuple when the action takes several values -- `--link
    CHILD PARENT` -- so it is flattened here rather than at each call site.
    """
    if isinstance(text, (tuple, list)):
        text = " ".join(str(t) for t in text)
    return (text or "").replace("'", "'\"'\"'").replace("[", "(").replace("]", ")")


def _describe(text: str) -> str:
    """Help text short enough to sit in a completion menu."""
    one_line = " ".join((text or "").split())
    return _zq(one_line[:70])


def _candidates(action: argparse.Action) -> list[str] | None:
    """Values to offer, from `choices` or from a `completions` attribute the
    parser attached -- the escape hatch for lists argparse must not validate
    against, like settings keys, where prefix matching is the point."""
    extra = getattr(action, "completions", None)
    if extra:
        return [str(c) for c in extra]
    if action.choices:
        return [str(c) for c in action.choices]
    return None


def _action_spec(action: argparse.Action) -> str | None:
    """One `_arguments` clause for one argparse action."""
    if isinstance(action, argparse._HelpAction):
        return None
    help_text = _describe(action.help or action.dest)

    if not action.option_strings:                       # positional
        placeholder = _zq(action.metavar or action.dest)
        completer = DYNAMIC.get(action.dest, "")
        cands = _candidates(action)
        if action.nargs in ("*", "+"):
            return f"'*:{placeholder}:{completer}'"
        if cands:
            return f"'1:{placeholder}:({' '.join(cands)})'"
        return f"'1:{placeholder}:{completer}'"

    takes_value = not isinstance(
        action, (argparse._StoreTrueAction, argparse._StoreFalseAction,
                 argparse._StoreConstAction, argparse._CountAction))
    value_part = ""
    if takes_value:
        meta = _zq(action.metavar or action.dest)
        cands = _candidates(action)
        if cands:
            value_part = f":{meta}:({' '.join(cands)})"
        elif action.dest in DYNAMIC:
            value_part = f":{meta}:{DYNAMIC[action.dest]}"
        else:
            value_part = f":{meta}:"

    opts = sorted(action.option_strings, key=len)
    if len(opts) > 1:
        joined = ",".join(opts)
        excl = " ".join(opts)
        return f"'({excl})'{{{joined}}}'[{help_text}]{value_part}'"
    return f"'{opts[0]}[{help_text}]{value_part}'"


def _subparsers(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def generate(parser: argparse.ArgumentParser) -> str:
    sub = _subparsers(parser)
    if sub is None:
        raise ValueError("parser has no subcommands to complete")

    helps = {a.dest: a.help for a in sub._choices_actions}
    out = [HEADER]
    for name, child in sub.choices.items():
        out.append(f"    '{name}:{_describe(helps.get(name) or child.description or name)}'\n")
    out.append("  )\n\n")
    out.append("  if (( CURRENT == 2 )); then\n"
               "    _describe 'command' subcmds\n"
               "    return\n"
               "  fi\n\n"
               "  case ${words[2]} in\n")

    for name, child in sub.choices.items():
        specs = [s for s in (_action_spec(a) for a in child._actions) if s]
        out.append(f"    {name})\n")
        if specs:
            out.append("      _arguments \\\n")
            out.append(" \\\n".join(f"        {s}" for s in specs) + "\n")
        else:
            out.append("      # no arguments\n")
        out.append("      ;;\n")
    out.append(FOOTER)
    return "".join(out)


def check(parser: argparse.ArgumentParser) -> tuple[bool, str]:
    """(in sync, generated text). The generated text is the source of truth."""
    text = generate(parser)
    on_disk = TARGET.read_text() if TARGET.exists() else ""
    return on_disk == text, text


def write(parser: argparse.ArgumentParser) -> Path:
    text = generate(parser)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text)
    return TARGET
